
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 12 22:48:15 CEST 2014
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon May 12 22:48:15 CEST 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\121\000\002\002\004\000\002\050\002\000\002\002" +
    "\004\000\002\003\005\000\002\003\003\000\002\004\002" +
    "\000\002\005\007\000\002\005\003\000\002\020\003\000" +
    "\002\020\003\000\002\020\003\000\002\043\003\000\002" +
    "\043\003\000\002\015\003\000\002\015\003\000\002\015" +
    "\003\000\002\006\003\000\002\007\004\000\002\007\003" +
    "\000\002\014\010\000\002\013\005\000\002\013\003\000" +
    "\002\010\004\000\002\010\003\000\002\016\012\000\002" +
    "\017\007\000\002\017\003\000\002\011\004\000\002\011" +
    "\003\000\002\021\006\000\002\012\004\000\002\012\003" +
    "\000\002\037\003\000\002\037\003\000\002\051\002\000" +
    "\002\040\015\000\002\042\007\000\002\042\005\000\002" +
    "\042\003\000\002\041\012\000\002\044\007\000\002\045" +
    "\005\000\002\045\003\000\002\046\003\000\002\046\003" +
    "\000\002\047\004\000\002\022\007\000\002\022\003\000" +
    "\002\023\005\000\002\023\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003\000\002\027\010\000\002\027\012\000\002\027\003" +
    "\000\002\030\014\000\002\026\005\000\002\031\003\000" +
    "\002\031\003\000\002\032\005\000\002\032\005\000\002" +
    "\033\005\000\002\033\005\000\002\033\005\000\002\033" +
    "\005\000\002\033\005\000\002\033\003\000\002\033\003" +
    "\000\002\033\003\000\002\033\003\000\002\025\006\000" +
    "\002\034\003\000\002\034\003\000\002\034\003\000\002" +
    "\035\006\000\002\036\005\000\002\036\003\000\002\036" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\006\003\000\022\000\001\002\000\004\002" +
    "\262\001\002\000\006\003\010\022\006\001\002\000\004" +
    "\045\256\001\002\000\004\002\uffff\001\002\000\020\002" +
    "\ufffd\003\ufffa\004\ufffa\013\ufffa\022\ufffa\030\ufffa\045\ufffa" +
    "\001\002\000\016\003\ufffc\004\ufffc\013\031\022\015\030" +
    "\025\045\032\001\002\000\012\003\uffe1\004\uffe1\013\uffe1" +
    "\022\uffe1\001\002\000\006\003\uffe5\004\uffe5\001\002\000" +
    "\014\003\ufffc\004\ufffc\013\031\022\015\045\032\001\002" +
    "\000\004\045\246\001\002\000\006\003\ufff1\004\ufff1\001" +
    "\002\000\006\003\240\004\241\001\002\000\016\003\ufffc" +
    "\004\ufffc\013\031\022\015\030\025\045\032\001\002\000" +
    "\012\003\uffe0\004\uffe0\013\uffe0\022\uffe0\001\002\000\012" +
    "\003\ufffc\004\ufffc\013\031\022\015\001\002\000\006\003" +
    "\uffea\004\uffea\001\002\000\016\003\ufffc\004\ufffc\013\031" +
    "\022\015\030\025\045\032\001\002\000\004\045\215\001" +
    "\002\000\006\003\uffe2\004\uffe2\001\002\000\004\043\206" +
    "\001\002\000\006\003\uffef\004\uffef\001\002\000\004\045" +
    "\035\001\002\000\006\041\033\043\uffec\001\002\000\004" +
    "\045\032\001\002\000\004\043\uffed\001\002\000\004\036" +
    "\036\001\002\000\006\037\ufffc\045\032\001\002\000\004" +
    "\043\177\001\002\000\004\037\042\001\002\000\004\037" +
    "\uffdb\001\002\000\004\025\043\001\002\000\006\005\045" +
    "\016\044\001\002\000\004\017\ufff6\001\002\000\004\017" +
    "\ufff5\001\002\000\004\017\uffdf\001\002\000\004\017\050" +
    "\001\002\000\014\004\ufffc\013\031\022\015\030\025\045" +
    "\032\001\002\000\004\004\052\001\002\000\020\003\066" +
    "\010\ufffc\012\072\014\060\023\055\025\057\045\070\001" +
    "\002\000\012\003\uffde\004\uffde\013\uffde\022\uffde\001\002" +
    "\000\004\042\uffcf\001\002\000\004\036\170\001\002\000" +
    "\004\042\uffce\001\002\000\016\011\107\027\102\036\106" +
    "\044\104\045\070\046\100\001\002\000\016\011\107\027" +
    "\102\036\106\044\104\045\070\046\100\001\002\000\004" +
    "\010\uffd7\001\002\000\032\015\uffc4\020\uffc4\021\uffc4\026" +
    "\uffc4\031\uffc4\032\uffc4\033\uffc4\034\uffc4\037\uffc4\040\uffc4" +
    "\041\uffc4\042\uffc4\001\002\000\004\010\153\001\002\000" +
    "\004\042\uffd6\001\002\000\004\042\uffcd\001\002\000\004" +
    "\042\uffc8\001\002\000\004\042\uffcc\001\002\000\036\015" +
    "\uffc5\020\uffc5\021\uffc5\026\uffc5\031\uffc5\032\uffc5\033\uffc5" +
    "\034\uffc5\035\141\036\142\037\uffc5\040\uffc5\041\uffc5\042" +
    "\uffc5\001\002\000\004\034\137\001\002\000\016\011\107" +
    "\027\102\036\106\044\104\045\070\046\100\001\002\000" +
    "\004\042\uffcb\001\002\000\004\042\076\001\002\000\004" +
    "\042\uffd5\001\002\000\020\003\066\010\ufffc\012\072\014" +
    "\060\023\055\025\057\045\070\001\002\000\004\010\uffd8" +
    "\001\002\000\030\015\uffba\020\uffba\021\uffba\026\uffba\031" +
    "\uffba\032\uffba\033\uffba\037\uffba\040\uffba\041\uffba\042\uffba" +
    "\001\002\000\030\015\uffbb\020\uffbb\021\uffbb\026\uffbb\031" +
    "\uffbb\032\uffbb\033\uffbb\037\uffbb\040\uffbb\041\uffbb\042\uffbb" +
    "\001\002\000\030\015\ufff3\020\ufff3\021\ufff3\026\ufff3\031" +
    "\ufff3\032\ufff3\033\ufff3\037\ufff3\040\ufff3\041\ufff3\042\ufff3" +
    "\001\002\000\030\015\uffb9\020\uffb9\021\uffb9\026\uffb9\031" +
    "\uffb9\032\uffb9\033\uffb9\037\uffb9\040\uffb9\041\uffb9\042\uffb9" +
    "\001\002\000\030\015\ufff4\020\ufff4\021\ufff4\026\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\037\ufff4\040\ufff4\041\ufff4\042\ufff4" +
    "\001\002\000\014\015\123\021\116\031\114\032\115\033" +
    "\113\001\002\000\016\011\107\027\102\036\106\044\104" +
    "\045\070\046\100\001\002\000\030\015\ufff2\020\ufff2\021" +
    "\ufff2\026\ufff2\031\ufff2\032\ufff2\033\ufff2\037\ufff2\040\ufff2" +
    "\041\ufff2\042\ufff2\001\002\000\030\015\uffbc\020\uffbc\021" +
    "\uffbc\026\uffbc\031\uffbc\032\uffbc\033\uffbc\037\uffbc\040\uffbc" +
    "\041\uffbc\042\uffbc\001\002\000\014\021\116\031\114\032" +
    "\115\033\113\037\112\001\002\000\030\015\uffbd\020\uffbd" +
    "\021\uffbd\026\uffbd\031\uffbd\032\uffbd\033\uffbd\037\uffbd\040" +
    "\uffbd\041\uffbd\042\uffbd\001\002\000\016\011\107\027\102" +
    "\036\106\044\104\045\070\046\100\001\002\000\016\011" +
    "\107\027\102\036\106\044\104\045\070\046\100\001\002" +
    "\000\016\011\107\027\102\036\106\044\104\045\070\046" +
    "\100\001\002\000\016\011\107\027\102\036\106\044\104" +
    "\045\070\046\100\001\002\000\030\015\uffbe\020\uffbe\021" +
    "\uffbe\026\uffbe\031\114\032\115\033\113\037\uffbe\040\uffbe" +
    "\041\uffbe\042\uffbe\001\002\000\030\015\uffc0\020\uffc0\021" +
    "\uffc0\026\uffc0\031\114\032\uffc0\033\uffc0\037\uffc0\040\uffc0" +
    "\041\uffc0\042\uffc0\001\002\000\030\015\uffc1\020\uffc1\021" +
    "\uffc1\026\uffc1\031\uffc1\032\uffc1\033\uffc1\037\uffc1\040\uffc1" +
    "\041\uffc1\042\uffc1\001\002\000\030\015\uffbf\020\uffbf\021" +
    "\uffbf\026\uffbf\031\114\032\115\033\uffbf\037\uffbf\040\uffbf" +
    "\041\uffbf\042\uffbf\001\002\000\016\011\107\027\102\036" +
    "\106\044\104\045\070\046\100\001\002\000\014\021\116" +
    "\031\114\032\115\033\113\040\125\001\002\000\016\011" +
    "\107\027\102\036\106\044\104\045\070\046\100\001\002" +
    "\000\014\020\127\021\116\031\114\032\115\033\113\001" +
    "\002\000\016\003\066\010\ufffc\012\072\014\060\023\055" +
    "\045\070\001\002\000\004\042\135\001\002\000\006\007" +
    "\uffd0\010\uffd0\001\002\000\004\010\133\001\002\000\004" +
    "\020\134\001\002\000\004\042\uffc7\001\002\000\020\003" +
    "\066\007\ufffc\010\ufffc\012\072\014\060\023\055\045\070" +
    "\001\002\000\006\007\uffd1\010\uffd1\001\002\000\016\011" +
    "\107\027\102\036\106\044\104\045\070\046\100\001\002" +
    "\000\014\021\116\031\114\032\115\033\113\042\uffc6\001" +
    "\002\000\004\045\151\001\002\000\020\011\107\027\102" +
    "\036\106\037\ufffc\044\104\045\070\046\100\001\002\000" +
    "\016\021\116\031\114\032\115\033\113\037\uffb2\041\147" +
    "\001\002\000\004\037\uffb1\001\002\000\004\037\146\001" +
    "\002\000\030\015\uffb4\020\uffb4\021\uffb4\026\uffb4\031\uffb4" +
    "\032\uffb4\033\uffb4\037\uffb4\040\uffb4\041\uffb4\042\uffb4\001" +
    "\002\000\020\011\107\027\102\036\106\037\ufffc\044\104" +
    "\045\070\046\100\001\002\000\004\037\uffb3\001\002\000" +
    "\034\015\uffc2\020\uffc2\021\uffc2\026\uffc2\031\uffc2\032\uffc2" +
    "\033\uffc2\034\uffc2\035\141\037\uffc2\040\uffc2\041\uffc2\042" +
    "\uffc2\001\002\000\032\015\uffc3\020\uffc3\021\uffc3\026\uffc3" +
    "\031\uffc3\032\uffc3\033\uffc3\034\uffc3\037\uffc3\040\uffc3\041" +
    "\uffc3\042\uffc3\001\002\000\004\045\154\001\002\000\004" +
    "\042\155\001\002\000\012\003\uffd9\004\uffd9\013\uffd9\022" +
    "\uffd9\001\002\000\014\021\116\026\157\031\114\032\115" +
    "\033\113\001\002\000\020\003\066\007\ufffc\010\ufffc\012" +
    "\072\014\060\023\055\045\070\001\002\000\006\007\161" +
    "\010\162\001\002\000\016\003\066\010\ufffc\012\072\014" +
    "\060\023\055\045\070\001\002\000\004\014\163\001\002" +
    "\000\004\042\uffca\001\002\000\004\010\165\001\002\000" +
    "\004\014\166\001\002\000\004\042\uffc9\001\002\000\014" +
    "\021\116\031\114\032\115\033\113\042\uffd4\001\002\000" +
    "\010\044\171\045\172\046\175\001\002\000\004\037\uffb6" +
    "\001\002\000\006\035\141\037\uffc5\001\002\000\004\037" +
    "\176\001\002\000\004\037\uffb5\001\002\000\004\037\uffb7" +
    "\001\002\000\004\042\uffb8\001\002\000\010\005\203\016" +
    "\200\045\202\001\002\000\006\037\ufff8\042\ufff8\001\002" +
    "\000\006\037\uffdc\042\204\001\002\000\006\037\ufff9\042" +
    "\ufff9\001\002\000\006\037\ufff7\042\ufff7\001\002\000\006" +
    "\037\ufffc\045\032\001\002\000\004\037\uffdd\001\002\000" +
    "\012\005\203\006\207\016\200\045\202\001\002\000\004" +
    "\034\212\001\002\000\004\042\211\001\002\000\014\003" +
    "\uffe4\004\uffe4\013\uffe4\022\uffe4\045\uffe4\001\002\000\010" +
    "\011\107\027\102\044\104\001\002\000\004\042\214\001" +
    "\002\000\016\003\uffee\004\uffee\013\uffee\022\uffee\030\uffee" +
    "\045\uffee\001\002\000\004\017\216\001\002\000\004\024" +
    "\217\001\002\000\006\010\ufffc\045\220\001\002\000\004" +
    "\043\226\001\002\000\004\010\223\001\002\000\004\010" +
    "\uffe7\001\002\000\004\024\224\001\002\000\004\042\225" +
    "\001\002\000\016\003\uffe9\004\uffe9\013\uffe9\022\uffe9\030" +
    "\uffe9\045\uffe9\001\002\000\010\005\203\016\200\045\202" +
    "\001\002\000\004\042\230\001\002\000\006\010\ufffc\045" +
    "\220\001\002\000\004\010\uffe8\001\002\000\006\003\ufff0" +
    "\004\ufff0\001\002\000\006\003\uffe3\004\uffe3\001\002\000" +
    "\004\043\236\001\002\000\006\003\uffeb\004\uffeb\001\002" +
    "\000\010\005\203\016\200\045\202\001\002\000\004\002" +
    "\ufffe\001\002\000\014\002\uffd2\003\uffd2\004\uffd2\013\uffd2" +
    "\022\uffd2\001\002\000\016\003\066\010\ufffc\012\072\014" +
    "\060\023\055\045\070\001\002\000\004\010\243\001\002" +
    "\000\004\045\244\001\002\000\004\042\245\001\002\000" +
    "\014\002\uffd3\003\uffd3\004\uffd3\013\uffd3\022\uffd3\001\002" +
    "\000\004\036\247\001\002\000\006\037\ufffc\045\032\001" +
    "\002\000\004\037\251\001\002\000\004\017\252\001\002" +
    "\000\016\003\ufffc\004\ufffc\013\031\022\015\030\025\045" +
    "\032\001\002\000\006\003\240\004\241\001\002\000\012" +
    "\003\uffda\004\uffda\013\uffda\022\uffda\001\002\000\006\003" +
    "\uffe6\004\uffe6\001\002\000\004\036\257\001\002\000\004" +
    "\037\260\001\002\000\004\017\261\001\002\000\016\003" +
    "\ufffb\004\ufffb\013\ufffb\022\ufffb\030\ufffb\045\ufffb\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\006\002\003\050\004\001\001\000\002\001" +
    "\001\000\006\003\006\005\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\004\025\006" +
    "\016\007\015\010\027\011\022\012\012\013\026\014\023" +
    "\016\017\021\013\037\021\040\011\041\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\004\025\011\254" +
    "\012\012\013\233\021\013\037\021\040\011\041\020\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\022\236" +
    "\001\001\000\026\004\025\010\234\011\022\012\012\013" +
    "\233\016\017\021\013\037\021\040\011\041\020\001\001" +
    "\000\002\001\001\000\014\004\025\012\232\037\021\040" +
    "\011\041\020\001\001\000\002\001\001\000\032\004\025" +
    "\007\231\010\027\011\022\012\012\013\026\014\023\016" +
    "\017\021\013\037\021\040\011\041\020\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\040\013\036\042\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\043" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\051\046\001\001\000\002\001\001\000\034\004\025\006" +
    "\050\007\015\010\027\011\022\012\012\013\026\014\023" +
    "\016\017\021\013\037\021\040\011\041\020\001\001\000" +
    "\004\044\052\001\001\000\032\004\060\024\063\025\053" +
    "\026\066\027\055\030\064\031\070\032\061\035\072\045" +
    "\062\046\073\047\074\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\015" +
    "\102\031\100\032\061\033\166\035\107\001\001\000\014" +
    "\015\102\031\100\032\061\033\155\035\107\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\015\102" +
    "\031\100\032\061\033\104\035\107\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\032\004\060" +
    "\024\063\025\053\026\066\027\055\030\064\031\070\032" +
    "\061\035\072\045\076\046\073\047\074\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\015\102\031\100\032\061\033\110\035\107\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\015\102\031\100\032\061\033" +
    "\121\035\107\001\001\000\014\015\102\031\100\032\061" +
    "\033\120\035\107\001\001\000\014\015\102\031\100\032" +
    "\061\033\117\035\107\001\001\000\014\015\102\031\100" +
    "\032\061\033\116\035\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\015\102\031\100\032\061\033\123\035\107\001\001\000" +
    "\002\001\001\000\014\015\102\031\100\032\061\033\125" +
    "\035\107\001\001\000\002\001\001\000\026\004\130\023" +
    "\131\024\127\025\053\026\066\027\055\030\064\031\070" +
    "\032\061\035\072\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\004\130\023\135\024\127\025\053\026\066\027" +
    "\055\030\064\031\070\032\061\035\072\001\001\000\002" +
    "\001\001\000\014\015\102\031\100\032\061\033\137\035" +
    "\107\001\001\000\002\001\001\000\004\032\151\001\001" +
    "\000\020\004\143\015\102\031\100\032\061\033\142\035" +
    "\107\036\144\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\004\143\015" +
    "\102\031\100\032\061\033\142\035\107\036\147\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\004\130\023\157\024\127\025\053\026" +
    "\066\027\055\030\064\031\070\032\061\035\072\001\001" +
    "\000\002\001\001\000\026\004\130\023\163\024\127\025" +
    "\053\026\066\027\055\030\064\031\070\032\061\035\072" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\031\173\032\061\034\172\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\020\200\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\004\040\013\036\042\204\001" +
    "\001\000\002\001\001\000\004\020\207\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\015" +
    "\212\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\004\221\017\220\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\226\001\001\000\002\001\001\000\006\004\221" +
    "\017\230\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\207\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\004\130\023\241\024\127\025\053\026\066\027\055" +
    "\030\064\031\070\032\061\035\072\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\004\040\013\036\042\247\001" +
    "\001\000\002\001\001\000\002\001\001\000\034\004\025" +
    "\006\252\007\015\010\027\011\022\012\012\013\026\014" +
    "\023\016\017\021\013\037\021\040\011\041\020\001\001" +
    "\000\004\022\253\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
    
    public void syntax_error(Symbol symbol)
    { 
        Token token = (Token) symbol.value;
        syntaxErrorManager.syntaxError ("Error sintactico", token);     
    }
        
    public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
    {   
        Token token = (Token) symbol.value;
        syntaxErrorManager.syntaxFatalError ("Error fatal", token);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


    
    SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
    SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
    ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
    FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // lista_parametros ::= vacio 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // lista_parametros ::= expresion 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // lista_parametros ::= expresion SEPARADOR_COMA lista_parametros 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // llamada_subprograma ::= IDENTIFICADOR ABRE_PARENTESIS lista_parametros CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamada_subprograma",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // parametro ::= referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // parametro ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // parametro ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentencia_entrada_salida ::= PUT_LINE ABRE_PARENTESIS parametro CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_entrada_salida",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= valor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= llamada_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= ABRE_PARENTESIS expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= expresion PLUS expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // acceso_registro ::= IDENTIFICADOR ACCESO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_registro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // acceso_registro ::= IDENTIFICADOR ACCESO acceso_registro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_registro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // referencia ::= acceso_registro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // referencia ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sentencia_asignacion ::= referencia ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // sentencia_for ::= FOR expresion IN expresion DELIMITADOR_RANGO expresion LOOP lista_sentencias END LOOP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_for",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentencia_if ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en sentencia if"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // sentencia_if ::= IF expresion THEN lista_sentencias ELSE lista_sentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // sentencia_if ::= IF expresion THEN lista_sentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // sentencia ::= llamada_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // sentencia ::= sentencia_asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sentencia ::= sentencia_for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia ::= sentencia_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia ::= sentencia_entrada_salida 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lista_sentencias ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // lista_sentencias ::= sentencia PUNTO_COMA lista_sentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cuerpo ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en cuerpo de procedimiento."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // cuerpo ::= BEGIN lista_sentencias END IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;
		
        semanticErrorManager.semanticDebug("Cierro ambito ");
        scopeManager.closeScope();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia_return ::= RETURN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_return",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia_funcion ::= sentencia_return 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_funcion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencia_funcion ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_funcion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_sentencias_funcion ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias_funcion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_sentencias_funcion ::= sentencia_funcion PUNTO_COMA lista_sentencias_funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias_funcion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cuerpo_funcion ::= BEGIN lista_sentencias_funcion END IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo_funcion",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // procedimiento ::= PROCEDURE IDENTIFICADOR ABRE_PARENTESIS parametros_subprograma CIERRA_PARENTESIS IS declaraciones cuerpo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procedimiento",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parametros_subprograma ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // parametros_subprograma ::= lista_nombres DOS_PUNTOS tipo 
            {
              Object RESULT =null;
		int listaNombresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listaNombresright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object listaNombres = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            ScopeIF scope = scopeManager.getCurrentScope();
            TypeTableIF tablaTipos = scope.getTypeTable();
            SymbolTableIF tablaSimbolos = scope.getSymbolTable();
            
            if (!scopeManager.containsType((String)tipo)) {
                semanticErrorManager.semanticFatalError("ERROR: tipo desconocido " + (String)tipo);
            } else {
	            ListaParametros listaParametros = new ListaParametros();
	            // Para cada nombre creo un parametro
	            for (Object objeto:((ListaObjetos)listaNombres).getVariables()) {
	               String nombreParametro = (String)objeto;
	                semanticErrorManager.semanticInfo("Declaracion de parametro " + nombreParametro);
	                if (scopeManager.containsSymbol(nombreParametro)) {
	                   semanticErrorManager.semanticFatalError("ERROR: parametro duplicado " + nombreParametro);
	                } else {
	                   semanticErrorManager.semanticDebug("Parametro valida, crea el simbolo");
	                   SymbolParameter sP = new SymbolParameter(scope, nombreParametro, tablaTipos.getType((String)tipo));
	                   tablaSimbolos.addSymbol(nombreParametro, sP);
	                   listaParametros.getListaParametros().add(sP);
	                }
	            }
	            RESULT = listaParametros;
            }        
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parametros_subprograma ::= lista_nombres DOS_PUNTOS tipo PUNTO_COMA parametros_subprograma 
            {
              Object RESULT =null;
		int listaNombresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int listaNombresright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object listaNombres = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listaParametrosPreviosleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listaParametrosPreviosright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object listaParametrosPrevios = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
		ScopeIF scope = scopeManager.getCurrentScope();
		TypeTableIF tablaTipos = scope.getTypeTable();
		SymbolTableIF tablaSimbolos = scope.getSymbolTable();
		
		if (!scopeManager.containsType((String)tipo)) {
		   semanticErrorManager.semanticFatalError("ERROR: tipo desconocido " + (String)tipo);
		} else {
		   ListaParametros listaParametros = new ListaParametros(((ListaParametros)listaParametrosPrevios).getListaParametros());
		   // Para cada nombre creo un parametro
		   for (Object objeto:((ListaObjetos)listaNombres).getVariables()) {
		       String nombreParametro = (String)objeto;
		       semanticErrorManager.semanticInfo("Declaracion de parametro " + nombreParametro + " tipo " + (String)tipo);
		       if (scopeManager.containsSymbol(nombreParametro)) {
		           semanticErrorManager.semanticFatalError("ERROR: parametro duplicado " + nombreParametro);
	           } else {
	               semanticErrorManager.semanticDebug("Parametro valida, crea el simbolo");
	               SymbolParameter sP = new SymbolParameter(scope, nombreParametro, tablaTipos.getType((String)tipo));
	               tablaSimbolos.addSymbol(nombreParametro, sP);
	               listaParametros.getListaParametros().add(sP);
	           }
	        }
	        RESULT = listaParametros;
	    }	    
	    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // funcion ::= FUNCTION IDENTIFICADOR ABRE_PARENTESIS parametros_subprograma CIERRA_PARENTESIS RETURN tipo_primitivo NT$1 IS declaraciones cuerpo_funcion 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idFuncionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int idFuncionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		Token idFuncion = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int listaParametrosleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int listaParametrosright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		Object listaParametros = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object tipoRetorno = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NT$1 ::= 
            {
              Object RESULT =null;
		int idFuncionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idFuncionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Token idFuncion = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int listaParametrosleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listaParametrosright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object listaParametros = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object tipoRetorno = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

        String nombreFuncion = idFuncion.getLexema();
        
        // Comprueba si la funcion ha sido declarada
        if (!(scopeManager.containsSymbol(nombreFuncion)
            && scopeManager.containsType(nombreFuncion))) {
            semanticErrorManager.semanticInfo("Declaracion de funcion " + nombreFuncion 
                                            + " en linea " + idFuncion.getLine());
            
            ScopeIF scope = scopeManager.getCurrentScope();
            TypeTableIF tablaTipos = scope.getTypeTable();
            SymbolTableIF tablaSimbolos = scope.getSymbolTable();
            
            //Creo un tipo y un simbolo para la funcion y los añado a la tabla
            TypeFunction tipoFuncion = new TypeFunction(scope, nombreFuncion);
            TypeIF tipoResultado = scopeManager.searchType((String)tipoRetorno);
            semanticErrorManager.semanticInfo("Retorna " + tipoResultado.getName());
            tipoFuncion.setTipoResultado(tipoResultado);
            tablaTipos.addType(nombreFuncion, tipoFuncion);
            SymbolFunction simboloFuncion = new SymbolFunction(scope, nombreFuncion, tipoFuncion);
            tablaSimbolos.addSymbol(nombreFuncion, simboloFuncion);
            
            // Abro un nuevo ambito para la funcion, con una nueva tabla simbolos y tipos
            semanticErrorManager.semanticInfo("Nuevo ambito " + nombreFuncion);
            ScopeIF scopeFuncion = scopeManager.openScope(nombreFuncion);
            TypeTableIF tablaTiposFuncion = scopeFuncion.getTypeTable();
            SymbolTableIF tablaSimbolosFuncion = scopeFuncion.getSymbolTable();
            

            for (SymbolParameter parametro:((ListaParametros)listaParametros).getListaParametros()) {
                semanticErrorManager.semanticInfo("Declaracion de parametro " + parametro.getName() 
                                + " de tipo " + parametro.getType().getName());
                tablaSimbolosFuncion.addSymbol(parametro.getName(),parametro);
                tipoFuncion.addTipoParametro(parametro.getType());
            }
        } else {
            semanticErrorManager.semanticFatalError("ERROR: Funcion ya declarada " + nombreFuncion
                                                    +" en linea: "+idFuncion.getLine());        }
        
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // subprograma ::= procedimiento 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxDebug("Declaracion procedimiento");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("subprograma",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // subprograma ::= funcion 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxDebug("Declaracion funcion");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("subprograma",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // declaracion_subprogramas ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_subprogramas",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // declaracion_subprogramas ::= subprograma declaracion_subprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_subprogramas",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // variable ::= lista_nombres DOS_PUNTOS tipo PUNTO_COMA 
            {
              Object RESULT =null;
		int objListaNombresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int objListaNombresright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object objListaNombres = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int objTipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int objTiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object objTipo = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        String tipoVariable = (String)objTipo;
        ListaObjetos listaNombres = (ListaObjetos)objListaNombres; 
        semanticErrorManager.semanticDebug("Declaracion variables de tipo " + tipoVariable);
        
        ScopeIF scope = scopeManager.getCurrentScope();
        TypeTableIF tablaTipos = scope.getTypeTable();
        SymbolTableIF tablaSimbolos = scope.getSymbolTable();
        
        // Si el tipo no existe, error
        if (!tablaTipos.containsType(tipoVariable)) {
            semanticErrorManager.semanticFatalError("ERROR: El tipo " 
                                + tipoVariable + 
                                " no ha sido definido en el programa");
        } else {
            semanticErrorManager.semanticDebug("Encontrado el tipo, valida que no haya nombres duplicados");
	        // Para cada nombre creo una variable
	        for (Object objeto:listaNombres.getVariables()) {
	           String nombreVar = (String)objeto;
	            semanticErrorManager.semanticInfo("Declaracion de variable " + nombreVar);
	            if (tablaSimbolos.containsSymbol(nombreVar)) {
	               semanticErrorManager.semanticFatalError("ERROR: variable duplicada " + nombreVar);
	            } else {
	               semanticErrorManager.semanticDebug("Variable valida, crea el simbolo");
	               SymbolVariable sV = new SymbolVariable(scope, nombreVar, tablaTipos.getType(tipoVariable));
	               tablaSimbolos.addSymbol(nombreVar, sV);
	            }
	        }
        }
        semanticErrorManager.semanticDebug("End declaracion variable");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracion_variables ::= declaracion_subprogramas 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxDebug("Declaracion subprogramas");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_variables",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declaracion_variables ::= variable declaracion_variables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_variables",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_campos ::= vacio 
            {
              ListaObjetos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_campos",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_campos ::= IDENTIFICADOR DOS_PUNTOS tipo PUNTO_COMA lista_campos 
            {
              ListaObjetos RESULT =null;
		int idCampoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idCamporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Token idCampo = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tipoCampoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tipoCamporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object tipoCampo = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listaCamposleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listaCamposright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ListaObjetos listaCampos = (ListaObjetos)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    // Añadir ID + tipo a lista de campos del registro registro
    ScopeIF scope = scopeManager.getCurrentScope();
    TypeTableIF tablaTipos = scope.getTypeTable();
    SymbolIF simbolo = new SymbolVariable(scope,
                                            idCampo.getLexema(),
                                            scopeManager.searchType(tipoCampo.toString()));
    CampoRegistro campo = new CampoRegistro(idCampo.getLexema(), idCampo.getLine(), 
                                            idCampo.getColumn(), simbolo);
    semanticErrorManager.semanticInfo("Identificado el campo " + campo.getNombre() + ". ");
    if (listaCampos == null) {
        listaCampos = new ListaObjetos();
    }
    listaCampos.add(campo);
    
    RESULT = listaCampos;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_campos",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // registro ::= TYPE IDENTIFICADOR IS RECORD lista_campos END RECORD PUNTO_COMA 
            {
              Object RESULT =null;
		int idRegistroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int idRegistroright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Token idRegistro = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int listaCamposRegistroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listaCamposRegistroright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ListaObjetos listaCamposRegistro = (ListaObjetos)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
        syntaxErrorManager.syntaxInfo("Declaracion de registro " + idRegistro.getLexema() + ". Linea " + idRegistro.getLine());
        // Comprueba en la tabla de tipos si el tipo ya está declarado
        ScopeIF scope = scopeManager.getCurrentScope();
        
        TypeTableIF typeTable = scope.getTypeTable();
        
        if (typeTable.containsType(idRegistro.getLexema())) {
            semanticErrorManager.semanticFatalError("Error: el tipo "+idRegistro.getLexema()+" en la linea: "+idRegistro.getLine()+" ya ha sido declarado");
        } else {
            TypeRecord tipoRegistro = new TypeRecord(scope, idRegistro.getLexema());
            typeTable.addType(tipoRegistro);
            syntaxErrorManager.syntaxInfo("Tipo registro " + idRegistro.getLexema() + ". Añadido en la tabla de tipos");
            // Compruebo los campos
        for (int i = 0; i<listaCamposRegistro.size();i++) {
            CampoRegistro c = (CampoRegistro) listaCamposRegistro.get(i);
            SymbolVariable var = (SymbolVariable) c.getSymbol();
            if (!tipoRegistro.containsCampo(c.getNombre())) {
                semanticErrorManager.semanticInfo("Se inserta el campo " + c.getNombre() + "linea " + c.getLinea() + "... ");
                tipoRegistro.addCampo(c.getNombre(), var); 
                semanticErrorManager.semanticInfo("...OK!");                                        
            } else {
                semanticErrorManager.semanticFatalError ("El campo: " + c.getNombre() +" en " + c.getLinea() + " ya ha sido definido.");
            }
        } 
        }
        
        
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("registro",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracion_registros ::= declaracion_variables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_registros",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracion_registros ::= registro declaracion_registros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_registros",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_nombres ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ListaObjetos listaNombres = new ListaObjetos();
        listaNombres.add(id.getLexema());
        RESULT = listaNombres;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_nombres",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_nombres ::= IDENTIFICADOR SEPARADOR_COMA lista_nombres 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listaNombresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listaNombresright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object listaNombres = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        semanticErrorManager.semanticInfo("Se encuentra el nombre " + id.getLexema()); 
        semanticErrorManager.semanticInfo("Se encuentra el listado " + listaNombres.toString());
        ListaObjetos listaResultado = new ListaObjetos((ListaObjetos)listaNombres);
        listaResultado.add(id.getLexema());
        RESULT = listaResultado;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_nombres",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // constante ::= lista_nombres DOS_PUNTOS CONSTANT ASIGNACION valor PUNTO_COMA 
            {
              Object RESULT =null;
		int listaNombresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int listaNombresright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object listaNombres = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        ScopeIF scope = scopeManager.getCurrentScope();
        String nombreConstante = (String)((ListaObjetos)listaNombres).get(0);
        semanticErrorManager.semanticInfo("Declaracion de constante " + nombreConstante);
        // comprueba si la constante ha sido declarada y se encuentra en la tabla de simbolos
        if (scope.getSymbolTable().containsSymbol(nombreConstante)) {
            semanticErrorManager.semanticFatalError("Error: la constante "+nombreConstante+" ya ha sido declarada");
        } else {
            // Creo la constante en el ambito
            SymbolTableIF tablaSimbolos = scope.getSymbolTable();
            String tipo = (String)v;
            SymbolConstant simboloCte = new SymbolConstant(scope,nombreConstante,scopeManager.searchType(tipo));
            // La guardo en la tabla de simbolos
            tablaSimbolos.addSymbol(nombreConstante, simboloCte);
            semanticErrorManager.semanticInfo("Constante " + nombreConstante + " " + tipo + " guardada en la tabla de simbolos");
        }
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("constante",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion_constantes ::= declaracion_registros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_constantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declaracion_constantes ::= constante declaracion_constantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_constantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaraciones ::= declaracion_constantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // valor ::= FALSE 
            {
              Object RESULT =null;
		 RESULT="BOOLEAN"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // valor ::= TRUE 
            {
              Object RESULT =null;
		 RESULT="BOOLEAN"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // valor ::= NUMERO 
            {
              Object RESULT =null;
		 RESULT="INTEGER"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_primitivo ::= BOOLEAN 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT="BOOLEAN"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_primitivo ::= INTEGER 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT="INTEGER"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT="BOOLEAN"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo ::= INTEGER 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT="INTEGER"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT=id.getLexema();
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // cabecera ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en declaracion de cabecera."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cabecera ::= PROCEDURE IDENTIFICADOR ABRE_PARENTESIS CIERRA_PARENTESIS IS 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
        //Crear el ámbito global del programa asociado al nombre del procedimiento.
        String name = id.getLexema();
        scopeManager.openScope(name);
        ScopeIF scope = scopeManager.getCurrentScope();
        semanticErrorManager.semanticDebug("Abierto ambito " + name);
        
        //******************* Ahora insertar tipos basicos en la tabla
        TypeTableIF tablaTipos = scope.getTypeTable();
        TypeSimple tipoBooleano = new TypeSimple(scope);
        tipoBooleano.setName("BOOLEAN");
        tablaTipos.addType(tipoBooleano);
        TypeSimple tipoEntero = new TypeSimple(scope);
        tipoEntero.setName("INTEGER");
        tablaTipos.addType(tipoEntero);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // vacio ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vacio",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= error 
            {
              Axiom RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en declaracion de procedimiento principal."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= cabecera declaraciones cuerpo 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        // No modificar esta estructura, aunque se pueden añadir más acciones semánticas
        
        List intermediateCode = ax.getIntermediateCode ();
        finalCodeFactory.create (intermediateCode);
                
        syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

