
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 10 19:13:43 CET 2014
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Feb 10 19:13:43 CET 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\124\000\002\002\004\000\002\052\002\000\002\002" +
    "\004\000\002\003\005\000\002\003\003\000\002\004\002" +
    "\000\002\005\007\000\002\005\003\000\002\006\003\000" +
    "\002\007\004\000\002\007\003\000\002\010\004\000\002" +
    "\010\003\000\002\011\004\000\002\011\003\000\002\012" +
    "\004\000\002\012\003\000\002\041\003\000\002\041\003" +
    "\000\002\042\014\000\002\044\007\000\002\044\005\000" +
    "\002\044\003\000\002\043\012\000\002\046\007\000\002" +
    "\047\005\000\002\047\003\000\002\050\003\000\002\050" +
    "\003\000\002\051\004\000\002\015\007\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\017\012\000" +
    "\002\020\004\000\002\020\003\000\002\021\006\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\045" +
    "\003\000\002\045\003\000\002\023\005\000\002\013\004" +
    "\000\002\014\005\000\002\014\003\000\002\024\007\000" +
    "\002\024\003\000\002\025\005\000\002\025\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\031\010\000\002\031\012" +
    "\000\002\031\003\000\002\032\014\000\002\030\005\000" +
    "\002\033\003\000\002\033\003\000\002\034\005\000\002" +
    "\034\005\000\002\035\005\000\002\035\005\000\002\035" +
    "\005\000\002\035\005\000\002\035\005\000\002\035\003" +
    "\000\002\035\003\000\002\035\003\000\002\035\003\000" +
    "\002\035\003\000\002\035\003\000\002\027\006\000\002" +
    "\036\003\000\002\036\003\000\002\036\003\000\002\037" +
    "\006\000\002\040\005\000\002\040\003\000\002\040\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\006\003\000\022\000\001\002\000\004\002" +
    "\263\001\002\000\006\003\010\022\006\001\002\000\004" +
    "\045\257\001\002\000\004\002\uffff\001\002\000\020\002" +
    "\ufffd\003\ufffa\004\ufffa\013\ufffa\022\ufffa\030\ufffa\045\ufffa" +
    "\001\002\000\016\003\ufffc\004\ufffc\013\020\022\012\030" +
    "\025\045\030\001\002\000\004\045\250\001\002\000\004" +
    "\043\247\001\002\000\012\003\uffef\004\uffef\013\uffef\022" +
    "\uffef\001\002\000\006\003\ufff7\004\ufff7\001\002\000\006" +
    "\003\ufff9\004\ufff9\001\002\000\016\003\ufffc\004\ufffc\013" +
    "\020\022\012\030\025\045\030\001\002\000\004\045\210" +
    "\001\002\000\012\005\160\006\201\016\155\045\157\001" +
    "\002\000\006\003\ufff1\004\ufff1\001\002\000\012\003\ufffc" +
    "\004\ufffc\013\020\022\012\001\002\000\006\003\ufff3\004" +
    "\ufff3\001\002\000\004\045\163\001\002\000\016\003\ufffc" +
    "\004\ufffc\013\020\022\012\030\025\045\030\001\002\000" +
    "\014\003\ufffc\004\ufffc\013\020\022\012\045\030\001\002" +
    "\000\006\041\151\043\uffd3\001\002\000\006\003\ufff5\004" +
    "\ufff5\001\002\000\006\003\035\004\036\001\002\000\012" +
    "\003\ufff0\004\ufff0\013\ufff0\022\ufff0\001\002\000\004\002" +
    "\ufffe\001\002\000\014\002\uffd1\003\uffd1\004\uffd1\013\uffd1" +
    "\022\uffd1\001\002\000\016\003\050\010\ufffc\012\037\014" +
    "\046\023\040\045\054\001\002\000\016\011\064\027\062" +
    "\036\065\044\063\045\054\046\060\001\002\000\004\036" +
    "\131\001\002\000\004\042\127\001\002\000\004\034\125" +
    "\001\002\000\032\015\uffc3\020\uffc3\021\uffc3\026\uffc3\031" +
    "\uffc3\032\uffc3\033\uffc3\034\uffc3\037\uffc3\040\uffc3\041\uffc3" +
    "\042\uffc3\001\002\000\004\042\uffcc\001\002\000\004\042" +
    "\uffcb\001\002\000\016\011\064\027\062\036\065\044\063" +
    "\045\054\046\060\001\002\000\006\007\uffcf\010\uffcf\001" +
    "\002\000\004\042\uffc7\001\002\000\004\042\uffce\001\002" +
    "\000\004\042\uffcd\001\002\000\004\010\111\001\002\000" +
    "\036\015\uffc4\020\uffc4\021\uffc4\026\uffc4\031\uffc4\032\uffc4" +
    "\033\uffc4\034\uffc4\035\056\036\057\037\uffc4\040\uffc4\041" +
    "\uffc4\042\uffc4\001\002\000\004\042\uffca\001\002\000\004" +
    "\045\107\001\002\000\020\011\064\027\062\036\065\037" +
    "\ufffc\044\063\045\054\046\060\001\002\000\030\015\uffb9" +
    "\020\uffb9\021\uffb9\026\uffb9\031\uffb9\032\uffb9\033\uffb9\037" +
    "\uffb9\040\uffb9\041\uffb9\042\uffb9\001\002\000\030\015\uffba" +
    "\020\uffba\021\uffba\026\uffba\031\uffba\032\uffba\033\uffba\037" +
    "\uffba\040\uffba\041\uffba\042\uffba\001\002\000\030\015\uffb8" +
    "\020\uffb8\021\uffb8\026\uffb8\031\uffb8\032\uffb8\033\uffb8\037" +
    "\uffb8\040\uffb8\041\uffb8\042\uffb8\001\002\000\030\015\uffb6" +
    "\020\uffb6\021\uffb6\026\uffb6\031\uffb6\032\uffb6\033\uffb6\037" +
    "\uffb6\040\uffb6\041\uffb6\042\uffb6\001\002\000\030\015\uffb7" +
    "\020\uffb7\021\uffb7\026\uffb7\031\uffb7\032\uffb7\033\uffb7\037" +
    "\uffb7\040\uffb7\041\uffb7\042\uffb7\001\002\000\016\011\064" +
    "\027\062\036\065\044\063\045\054\046\060\001\002\000" +
    "\004\037\uffae\001\002\000\016\021\077\031\074\032\075" +
    "\033\073\037\uffaf\041\076\001\002\000\004\037\072\001" +
    "\002\000\030\015\uffbb\020\uffbb\021\uffbb\026\uffbb\031\uffbb" +
    "\032\uffbb\033\uffbb\037\uffbb\040\uffbb\041\uffbb\042\uffbb\001" +
    "\002\000\030\015\uffb1\020\uffb1\021\uffb1\026\uffb1\031\uffb1" +
    "\032\uffb1\033\uffb1\037\uffb1\040\uffb1\041\uffb1\042\uffb1\001" +
    "\002\000\016\011\064\027\062\036\065\044\063\045\054" +
    "\046\060\001\002\000\016\011\064\027\062\036\065\044" +
    "\063\045\054\046\060\001\002\000\016\011\064\027\062" +
    "\036\065\044\063\045\054\046\060\001\002\000\020\011" +
    "\064\027\062\036\065\037\ufffc\044\063\045\054\046\060" +
    "\001\002\000\016\011\064\027\062\036\065\044\063\045" +
    "\054\046\060\001\002\000\030\015\uffbd\020\uffbd\021\uffbd" +
    "\026\uffbd\031\074\032\075\033\073\037\uffbd\040\uffbd\041" +
    "\uffbd\042\uffbd\001\002\000\004\037\uffb0\001\002\000\030" +
    "\015\uffbf\020\uffbf\021\uffbf\026\uffbf\031\074\032\uffbf\033" +
    "\uffbf\037\uffbf\040\uffbf\041\uffbf\042\uffbf\001\002\000\030" +
    "\015\uffc0\020\uffc0\021\uffc0\026\uffc0\031\uffc0\032\uffc0\033" +
    "\uffc0\037\uffc0\040\uffc0\041\uffc0\042\uffc0\001\002\000\030" +
    "\015\uffbe\020\uffbe\021\uffbe\026\uffbe\031\074\032\075\033" +
    "\uffbe\037\uffbe\040\uffbe\041\uffbe\042\uffbe\001\002\000\014" +
    "\021\077\031\074\032\075\033\073\037\106\001\002\000" +
    "\030\015\uffbc\020\uffbc\021\uffbc\026\uffbc\031\uffbc\032\uffbc" +
    "\033\uffbc\037\uffbc\040\uffbc\041\uffbc\042\uffbc\001\002\000" +
    "\034\015\uffc1\020\uffc1\021\uffc1\026\uffc1\031\uffc1\032\uffc1" +
    "\033\uffc1\034\uffc1\035\056\037\uffc1\040\uffc1\041\uffc1\042" +
    "\uffc1\001\002\000\032\015\uffc2\020\uffc2\021\uffc2\026\uffc2" +
    "\031\uffc2\032\uffc2\033\uffc2\034\uffc2\037\uffc2\040\uffc2\041" +
    "\uffc2\042\uffc2\001\002\000\004\045\112\001\002\000\004" +
    "\042\113\001\002\000\014\002\uffd2\003\uffd2\004\uffd2\013" +
    "\uffd2\022\uffd2\001\002\000\014\021\077\026\115\031\074" +
    "\032\075\033\073\001\002\000\020\003\050\007\ufffc\010" +
    "\ufffc\012\037\014\046\023\040\045\054\001\002\000\006" +
    "\007\117\010\120\001\002\000\016\003\050\010\ufffc\012" +
    "\037\014\046\023\040\045\054\001\002\000\004\014\121" +
    "\001\002\000\004\042\uffc9\001\002\000\004\010\123\001" +
    "\002\000\004\014\124\001\002\000\004\042\uffc8\001\002" +
    "\000\016\011\064\027\062\036\065\044\063\045\054\046" +
    "\060\001\002\000\014\021\077\031\074\032\075\033\073" +
    "\042\uffc5\001\002\000\020\003\050\007\ufffc\010\ufffc\012" +
    "\037\014\046\023\040\045\054\001\002\000\006\007\uffd0" +
    "\010\uffd0\001\002\000\010\044\132\045\133\046\136\001" +
    "\002\000\004\037\uffb3\001\002\000\006\035\056\037\uffc4" +
    "\001\002\000\004\037\137\001\002\000\004\037\uffb2\001" +
    "\002\000\004\037\uffb4\001\002\000\004\042\uffb5\001\002" +
    "\000\014\015\141\021\077\031\074\032\075\033\073\001" +
    "\002\000\016\011\064\027\062\036\065\044\063\045\054" +
    "\046\060\001\002\000\014\021\077\031\074\032\075\033" +
    "\073\040\143\001\002\000\016\011\064\027\062\036\065" +
    "\044\063\045\054\046\060\001\002\000\014\020\145\021" +
    "\077\031\074\032\075\033\073\001\002\000\016\003\050" +
    "\010\ufffc\012\037\014\046\023\040\045\054\001\002\000" +
    "\004\010\147\001\002\000\004\020\150\001\002\000\004" +
    "\042\uffc6\001\002\000\004\045\030\001\002\000\004\043" +
    "\uffd4\001\002\000\006\003\ufff4\004\ufff4\001\002\000\010" +
    "\005\160\016\155\045\157\001\002\000\006\037\uffda\042" +
    "\uffda\001\002\000\004\042\161\001\002\000\006\037\uffdb" +
    "\042\uffdb\001\002\000\006\037\uffd9\042\uffd9\001\002\000" +
    "\014\003\uffd6\004\uffd6\013\uffd6\022\uffd6\045\uffd6\001\002" +
    "\000\006\003\ufff6\004\ufff6\001\002\000\004\017\164\001" +
    "\002\000\004\024\165\001\002\000\004\045\167\001\002" +
    "\000\006\010\uffdd\045\167\001\002\000\004\043\174\001" +
    "\002\000\004\010\171\001\002\000\004\024\172\001\002" +
    "\000\004\042\173\001\002\000\016\003\uffdf\004\uffdf\013" +
    "\uffdf\022\uffdf\030\uffdf\045\uffdf\001\002\000\010\005\160" +
    "\016\155\045\157\001\002\000\004\042\176\001\002\000" +
    "\006\010\uffdc\045\uffdc\001\002\000\004\010\uffde\001\002" +
    "\000\006\003\ufff2\004\ufff2\001\002\000\004\034\202\001" +
    "\002\000\010\011\206\027\205\044\203\001\002\000\004" +
    "\042\uffe0\001\002\000\004\042\207\001\002\000\004\042" +
    "\uffe2\001\002\000\004\042\uffe1\001\002\000\016\003\uffe3" +
    "\004\uffe3\013\uffe3\022\uffe3\030\uffe3\045\uffe3\001\002\000" +
    "\004\036\211\001\002\000\006\037\ufffc\045\030\001\002" +
    "\000\004\043\242\001\002\000\004\037\215\001\002\000" +
    "\004\037\uffeb\001\002\000\004\025\216\001\002\000\006" +
    "\005\220\016\217\001\002\000\004\017\uffd8\001\002\000" +
    "\004\017\uffd7\001\002\000\004\017\222\001\002\000\014" +
    "\004\ufffc\013\020\022\012\030\025\045\030\001\002\000" +
    "\004\004\225\001\002\000\012\003\uffee\004\uffee\013\uffee" +
    "\022\uffee\001\002\000\020\003\050\010\ufffc\012\037\014" +
    "\046\023\040\025\226\045\054\001\002\000\016\011\064" +
    "\027\062\036\065\044\063\045\054\046\060\001\002\000" +
    "\004\010\uffe7\001\002\000\004\010\236\001\002\000\004" +
    "\042\uffe6\001\002\000\004\042\234\001\002\000\004\042" +
    "\uffe5\001\002\000\020\003\050\010\ufffc\012\037\014\046" +
    "\023\040\025\226\045\054\001\002\000\004\010\uffe8\001" +
    "\002\000\004\045\237\001\002\000\004\042\240\001\002" +
    "\000\012\003\uffe9\004\uffe9\013\uffe9\022\uffe9\001\002\000" +
    "\014\021\077\031\074\032\075\033\073\042\uffe4\001\002" +
    "\000\010\005\160\016\155\045\157\001\002\000\006\037" +
    "\uffec\042\244\001\002\000\006\037\ufffc\045\030\001\002" +
    "\000\004\037\uffed\001\002\000\006\003\ufff8\004\ufff8\001" +
    "\002\000\012\005\uffd5\006\uffd5\016\uffd5\045\uffd5\001\002" +
    "\000\004\036\251\001\002\000\006\037\ufffc\045\030\001" +
    "\002\000\004\037\253\001\002\000\004\017\254\001\002" +
    "\000\016\003\ufffc\004\ufffc\013\020\022\012\030\025\045" +
    "\030\001\002\000\006\003\035\004\036\001\002\000\012" +
    "\003\uffea\004\uffea\013\uffea\022\uffea\001\002\000\004\036" +
    "\260\001\002\000\004\037\261\001\002\000\004\017\262" +
    "\001\002\000\016\003\ufffb\004\ufffb\013\ufffb\022\ufffb\030" +
    "\ufffb\045\ufffb\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\006\002\003\052\004\001\001\000\002\001" +
    "\001\000\006\003\006\005\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\036\004\021\006" +
    "\031\007\015\010\014\011\030\012\023\013\020\014\012" +
    "\015\016\017\025\023\026\041\022\042\032\043\013\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\004\021\007" +
    "\245\010\014\011\030\012\023\013\020\014\012\015\016" +
    "\017\025\023\026\041\022\042\032\043\013\001\001\000" +
    "\002\001\001\000\004\022\155\001\001\000\002\001\001" +
    "\000\014\004\021\012\177\041\022\042\032\043\013\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\004\021" +
    "\010\161\011\030\012\023\013\153\014\012\017\025\023" +
    "\026\041\022\042\032\043\013\001\001\000\024\004\021" +
    "\011\152\012\023\013\153\014\012\023\026\041\022\042" +
    "\032\043\013\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\024\033\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\004\046\025\052\026\040" +
    "\027\050\030\044\031\051\032\043\033\041\034\042\037" +
    "\054\001\001\000\012\033\060\034\042\035\137\037\070" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\033\060\034\042\035\113\037\070\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\034\107\001\001\000\016\004\065\033\060" +
    "\034\042\035\066\037\070\040\067\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\033\060\034\042\035\104\037" +
    "\070\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\033" +
    "\060\034\042\035\103\037\070\001\001\000\012\033\060" +
    "\034\042\035\102\037\070\001\001\000\012\033\060\034" +
    "\042\035\101\037\070\001\001\000\016\004\065\033\060" +
    "\034\042\035\066\037\070\040\100\001\001\000\012\033" +
    "\060\034\042\035\077\037\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\004\046" +
    "\025\115\026\040\027\050\030\044\031\051\032\043\033" +
    "\041\034\042\037\054\001\001\000\002\001\001\000\026" +
    "\004\046\025\121\026\040\027\050\030\044\031\051\032" +
    "\043\033\041\034\042\037\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\033\060\034\042\035\125\037\070" +
    "\001\001\000\002\001\001\000\026\004\046\025\127\026" +
    "\040\027\050\030\044\031\051\032\043\033\041\034\042" +
    "\037\054\001\001\000\002\001\001\000\010\033\134\034" +
    "\042\036\133\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\033\060\034\042" +
    "\035\141\037\070\001\001\000\002\001\001\000\012\033" +
    "\060\034\042\035\143\037\070\001\001\000\002\001\001" +
    "\000\026\004\046\025\145\026\040\027\050\030\044\031" +
    "\051\032\043\033\041\034\042\037\054\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\151\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\155\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\020" +
    "\167\021\165\001\001\000\006\020\176\021\165\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\174\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\016\203\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\004\213\014\211\044\212\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\045\220\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\036\004\021\006\222\007\015\010\014" +
    "\011\030\012\023\013\020\014\012\015\016\017\025\023" +
    "\026\041\022\042\032\043\013\001\001\000\004\046\223" +
    "\001\001\000\002\001\001\000\032\004\226\026\230\027" +
    "\050\030\044\031\051\032\043\033\041\034\042\037\054" +
    "\047\227\050\231\051\232\001\001\000\012\033\060\034" +
    "\042\035\240\037\070\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\004\226\026\230\027\050\030\044\031\051" +
    "\032\043\033\041\034\042\037\054\047\234\050\231\051" +
    "\232\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\022" +
    "\242\001\001\000\002\001\001\000\010\004\213\014\211" +
    "\044\244\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\004\213\014\211" +
    "\044\251\001\001\000\002\001\001\000\002\001\001\000" +
    "\036\004\021\006\254\007\015\010\014\011\030\012\023" +
    "\013\020\014\012\015\016\017\025\023\026\041\022\042" +
    "\032\043\013\001\001\000\004\024\255\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
    
    public void syntax_error(Symbol symbol)
    { 
        Token token = (Token) symbol.value;
        syntaxErrorManager.syntaxError ("Error sintactico", token);     
    }
        
    public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
    {   
        Token token = (Token) symbol.value;
        syntaxErrorManager.syntaxFatalError ("Error fatal", token);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


    
    SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
//    SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
//    ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
    FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // lista_parametros ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // lista_parametros ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // lista_parametros ::= expresion SEPARADOR_COMA lista_parametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // llamada_subprograma ::= IDENTIFICADOR ABRE_PARENTESIS lista_parametros CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamada_subprograma",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // parametro ::= referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // parametro ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // parametro ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sentencia_entrada_salida ::= PUT_LINE ABRE_PARENTESIS parametro CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_entrada_salida",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expresion ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expresion ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= llamada_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= ABRE_PARENTESIS expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= expresion PLUS expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // acceso_registro ::= IDENTIFICADOR ACCESO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_registro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // acceso_registro ::= IDENTIFICADOR ACCESO acceso_registro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_registro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // referencia ::= acceso_registro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // referencia ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentencia_asignacion ::= referencia ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sentencia_for ::= FOR expresion IN expresion DELIMITADOR_RANGO expresion LOOP lista_sentencias END LOOP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_for",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // sentencia_if ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en sentencia if"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentencia_if ::= IF expresion THEN lista_sentencias ELSE lista_sentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // sentencia_if ::= IF expresion THEN lista_sentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // sentencia ::= llamada_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // sentencia ::= sentencia_asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // sentencia ::= sentencia_for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sentencia ::= sentencia_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia ::= sentencia_entrada_salida 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // lista_sentencias ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lista_sentencias ::= sentencia PUNTO_COMA lista_sentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // cuerpo ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en cuerpo de procedimiento."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cuerpo ::= BEGIN lista_sentencias END IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // lista_nombres ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_nombres",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_nombres ::= IDENTIFICADOR SEPARADOR_COMA lista_nombres 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_nombres",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // inicio_declaracion ::= lista_nombres DOS_PUNTOS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio_declaracion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // variable ::= inicio_declaracion tipo PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tipo_primitivo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // tipo_primitivo ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tipo ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // tipo ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // campo ::= IDENTIFICADOR DOS_PUNTOS tipo PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("campo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_campos ::= campo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_campos",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_campos ::= campo lista_campos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_campos",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // registro ::= TYPE IDENTIFICADOR IS RECORD lista_campos END RECORD PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("registro",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // valor ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // valor ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // valor ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // constante ::= inicio_declaracion CONSTANT ASIGNACION valor PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("constante",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_return ::= RETURN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_return",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_funcion ::= sentencia_return 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_funcion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia_funcion ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia_funcion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_sentencias_funcion ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias_funcion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_sentencias_funcion ::= sentencia_funcion PUNTO_COMA lista_sentencias_funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias_funcion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cuerpo_funcion ::= BEGIN lista_sentencias_funcion END IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo_funcion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // procedimiento ::= PROCEDURE IDENTIFICADOR ABRE_PARENTESIS parametros_subprograma CIERRA_PARENTESIS IS declaraciones cuerpo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procedimiento",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // parametros_subprograma ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // parametros_subprograma ::= lista_nombres DOS_PUNTOS tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // parametros_subprograma ::= lista_nombres DOS_PUNTOS tipo PUNTO_COMA parametros_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros_subprograma",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // funcion ::= FUNCTION IDENTIFICADOR ABRE_PARENTESIS parametros_subprograma CIERRA_PARENTESIS RETURN tipo_primitivo IS declaraciones cuerpo_funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // subprograma ::= procedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subprograma",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // subprograma ::= funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subprograma",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion_subprogramas ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_subprogramas",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion_subprogramas ::= subprograma declaracion_subprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_subprogramas",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracion_variables ::= declaracion_subprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_variables",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_variables ::= variable declaracion_variables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_variables",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_registros ::= declaracion_variables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_registros",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_registros ::= registro declaracion_registros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_registros",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracion_constantes ::= declaracion_registros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_constantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion_constantes ::= constante declaracion_constantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_constantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaraciones ::= declaracion_constantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // cabecera ::= error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en declaracion de cabecera."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cabecera ::= PROCEDURE IDENTIFICADOR ABRE_PARENTESIS CIERRA_PARENTESIS IS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // vacio ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vacio",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= error 
            {
              Axiom RESULT =null;
		 syntaxErrorManager.syntaxDebug ("Error en declaracion de procedimiento principal."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= cabecera declaraciones cuerpo 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        // No modificar esta estructura, aunque se pueden añadir más acciones semánticas
        
        //List intermediateCode = ax.getIntermediateCode ();
        //finalCodeFactory.create (intermediateCode);

        
        syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

