
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 16 20:21:17 CEST 2014
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int NUMERO = 34;
  public static final int FUNCTION = 9;
  public static final int CIERRA_PARENTESIS = 29;
  public static final int INTEGER = 12;
  public static final int DOS_PUNTOS = 33;
  public static final int ABRE_PARENTESIS = 28;
  public static final int FOR = 8;
  public static final int IDENTIFICADOR = 35;
  public static final int IS = 13;
  public static final int IGUAL = 25;
  public static final int RECORD = 18;
  public static final int TYPE = 22;
  public static final int IN = 11;
  public static final int OR = 15;
  public static final int BEGIN = 2;
  public static final int PUT_LINE = 17;
  public static final int LOOP = 14;
  public static final int PLUS = 23;
  public static final int IF = 10;
  public static final int PUNTO_COMA = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int SEPARADOR_COMA = 31;
  public static final int RETURN = 19;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int CADENA = 36;
  public static final int CONSTANT = 4;
  public static final int ASIGNACION = 26;
  public static final int MAYOR = 24;
  public static final int ELSE = 5;
  public static final int DELIMITADOR_RANGO = 30;
  public static final int ACCESO = 27;
  public static final int THEN = 20;
  public static final int END = 6;
  public static final int FALSE = 7;
  public static final int PROCEDURE = 16;
}

