
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 05 16:10:17 CET 2013
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PUT_LINE = 25;
  public static final int PROCEDURE = 20;
  public static final int IS = 17;
  public static final int PLUS = 2;
  public static final int CADENA = 10;
  public static final int OR = 5;
  public static final int IGUAL = 4;
  public static final int THEN = 23;
  public static final int IN = 15;
  public static final int LOOP = 18;
  public static final int RETURN = 22;
  public static final int FUNCTION = 13;
  public static final int IF = 14;
  public static final int LITERAL_LOGICO = 9;
  public static final int ACCESO = 7;
  public static final int OF = 19;
  public static final int TYPE = 24;
  public static final int ASIGNACION = 6;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int RECORD = 21;
  public static final int LITERAL_ENTERO = 8;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 11;
  public static final int INTEGER = 16;
  public static final int FOR = 12;
}

